from django.urls import path
from . import views_users

urlpatterns = [
    path('log-files', views_users.log_files),
    path('log-details', views_users.log_file_details),
    path('logs-file-clear', views_users.clear_log_file),
    path('providers-list', views_users.providers_list),
    path('', views_users.list_or_create),
    path('clients', views_users.get_all_clients),
    path('providers', views_users.get_all_providers),
    path('system-users', views_users.get_all_system_users),
    path('me', views_users.me),
    path('current-user-info', views_users.current_user_info),
    path('provider-services-locations/<int:providerId>', views_users.provider_services_locations),
    path('provider-add-services-locations', views_users.provider_add_services_locations),
    path('provider-remove-services-locations', views_users.provider_remove_services_locations),
    path('send-otp', views_users.send_otp),
    path('verify-otp', views_users.verify_otp),
    path('email-otp-verification', views_users.email_otp_verification),
    path('resend-email-otp', views_users.resend_email_otp),
    path('verify-email', views_users.verify_email),
    path('resend-email', views_users.resend_email),
    path('forgot-password', views_users.forgot_password),
    path('reset-password', views_users.reset_password),
    path('user-type', views_users.user_type_update),
    path('provider-type', views_users.provider_type_update),
    path('provider-type', views_users.get_provider_types),
    path('change-password', views_users.change_password),
    path('request-email-update', views_users.request_email_update),
    path('confirm-email-update', views_users.confirm_email_update),
    path('app/logout', views_users.app_logout),
    path('admin', views_users.create_admin),
    path('admin/profile', views_users.admin_profile),
    path('admin/provider-document/<int:providerId>', views_users.update_provider_document),
    path('admin/payout-info-provider', views_users.payout_info),
    path('admin/generate-password/<int:id>', views_users.generate_user_password_by_admin),
    path('admin/delete-account/<int:userId>', views_users.delete_user_account_by_admin),
    path('delete-account', views_users.delete_my_account),
    path('provider/<int:providerId>', views_users.get_provider_details),
    path('client', views_users.update_client_profile),
    path('provider', views_users.update_provider_profile),
    path('provider-profile-update', views_users.provider_profile_update_new),
    path('client/<int:userId>', views_users.update_client_profile_by_id),
    path('provider-profile-update/<int:userId>', views_users.provider_profile_update_by_id),
    path('admin/profile', views_users.update_admin_profile),
    path('admin/payout-info-provider', views_users.update_payout_info),
    path('<int:userId>', views_users.user_detail),
]
