from django.urls import path
from . import views

urlpatterns = [
    path('', views.payment_view),
    path('create-card-token', views.create_card_token),
    path('create-bank-account-token', views.create_bank_account_token),
    path('customer-add-new-card', views.payment_view),
    path('customer-cards-list', views.payment_view),
    path('customer-card-details/<int:cardId>', views.payment_view),
    path('customer-details', views.payment_view),
    path('customer-set-default-card/<int:cardId>', views.payment_view),
    path('customer-update-card/<int:cardId>', views.payment_view),
    path('customer-update', views.payment_view),
    path('customer-delete-card/<int:cardId>', views.payment_view),
    path('check-stripe-account', views.payment_view),
    path('create-stripe-account', views.payment_view),
    path('update-stripe-account', views.payment_view),
    path('create-bank-account', views.payment_view),
    path('update-bank-account/<int:id>', views.payment_view),
    path('delete-bank-account/<int:id>', views.payment_view),
    path('stripe-account-details', views.payment_view),
    path('bank-account-details/<int:id>', views.payment_view),
    path('bank-accounts-list', views.payment_view),
    path('tax/register', views.tax_register),
    path('tax/register/update/<int:id>', views.tax_register_update),
    path('tax/register/list', views.tax_register_list),
    path('tax/calculate/<int:id>', views.tax_calculate),
    path('tax/calculate', views.get_calculated_tax),
    path('calculate-service-fee-and-tax', views.calculate_service_fee_and_tax),
    path('client-calculate-service-fee-and-tax', views.client_quote_tax),
    path('calculate-subscription-tax', views.subscription_tax),
    path('calculate-tax', views.calculate_tax),
    path('create-payment-method', views.payment_view),
    path('list-payment-methods', views.payment_view),
]
